//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dust765UO.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dust765UO.Resources.ResErrorMessages", typeof(ResErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Another character from this account is currently online in this world.  You must either log in as that character or wait for it to time out..
        /// </summary>
        public static string AnotherCharacterOnline {
            get {
                return ResourceManager.GetString("AnotherCharacterOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This character already exists.
        ///Playing....
        /// </summary>
        public static string CharacterAlreadyExists {
            get {
                return ResourceManager.GetString("CharacterAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This character does not exist anymore.  You will have to recreate it..
        /// </summary>
        public static string CharacterDoesNotExist {
            get {
                return ResourceManager.GetString("CharacterDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a That character is not old enough to delete. The character must be 7 days old before it can be deleted..
        /// </summary>
        public static string CharacterIsNotOldEnough {
            get {
                return ResourceManager.GetString("CharacterIsNotOldEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a That character is currently queued for backup and cannot be deleted..
        /// </summary>
        public static string CharacterIsQueuedForBackup {
            get {
                return ResourceManager.GetString("CharacterIsQueuedForBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a That character password is invalid..
        /// </summary>
        public static string CharacterPasswordInvalid {
            get {
                return ResourceManager.GetString("CharacterPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Character transfer in progress..
        /// </summary>
        public static string CharacterTransferInProgress {
            get {
                return ResourceManager.GetString("CharacterTransferInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The client could not attach to the game server. It must have been taken down, please wait a few minutes and try again..
        /// </summary>
        public static string ClientCouldNotAttachToServer {
            get {
                return ResourceManager.GetString("ClientCouldNotAttachToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{0}&apos; is not a valid UO directory.
        /// </summary>
        public static string ClientPathIsNotAValidUODirectory {
            get {
                return ResourceManager.GetString("ClientPathIsNotAValidUODirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Communication problem..
        /// </summary>
        public static string CommunicationProblem {
            get {
                return ResourceManager.GetString("CommunicationProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not attach to game server..
        /// </summary>
        public static string CouldNotAttachServer {
            get {
                return ResourceManager.GetString("CouldNotAttachServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Couldn&apos;t carry out your request..
        /// </summary>
        public static string CouldntCarryOutYourRequest {
            get {
                return ResourceManager.GetString("CouldntCarryOutYourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Couldn&apos;t connect to Ultima Online.  Please try again in a few moments..
        /// </summary>
        public static string CouldntConnectToUO {
            get {
                return ResourceManager.GetString("CouldntConnectToUO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error has occurred in the synchronization between the login servers and this world.  Please close your client and try again..
        /// </summary>
        public static string ErrorInSynchronization {
            get {
                return ResourceManager.GetString("ErrorInSynchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a General IGR authentication failure..
        /// </summary>
        public static string GeneralIGRAuthenticationFailure {
            get {
                return ResourceManager.GetString("GeneralIGRAuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You have been idle for too long.  If you do not do anything in the next minute, you will be logged out..
        /// </summary>
        public static string IdleTooLong {
            get {
                return ResourceManager.GetString("IdleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incorrect name/password..
        /// </summary>
        public static string IncorrectNamePassword {
            get {
                return ResourceManager.GetString("IncorrectNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incorrect password.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Someone is already using this account..
        /// </summary>
        public static string SomeoneIsAlreadyUsingThisAccount {
            get {
                return ResourceManager.GetString("SomeoneIsAlreadyUsingThisAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a That character does not exist..
        /// </summary>
        public static string ThatCharacterDoesNotExist {
            get {
                return ResourceManager.GetString("ThatCharacterDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a That character is being played right now..
        /// </summary>
        public static string ThatCharacterIsBeingPlayed {
            get {
                return ResourceManager.GetString("ThatCharacterIsBeingPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a That is out of sight..
        /// </summary>
        public static string ThatIsOutOfSight {
            get {
                return ResourceManager.GetString("ThatIsOutOfSight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a That is too far away..
        /// </summary>
        public static string ThatIsTooFarAway {
            get {
                return ResourceManager.GetString("ThatIsTooFarAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a That item does not belong to you.  You&apos;ll have to steal it..
        /// </summary>
        public static string ThatItemDoesNotBelongToYou {
            get {
                return ResourceManager.GetString("ThatItemDoesNotBelongToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The IGR concurrency limit has been met..
        /// </summary>
        public static string TheIGRConcurrencyLimitHasBeenMet {
            get {
                return ResourceManager.GetString("TheIGRConcurrencyLimitHasBeenMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The IGR time limit has been met..
        /// </summary>
        public static string TheIGRTimeLimitHasBeenMet {
            get {
                return ResourceManager.GetString("TheIGRTimeLimitHasBeenMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You are already holding an item..
        /// </summary>
        public static string YouAreAlreadyHoldingAnItem {
            get {
                return ResourceManager.GetString("YouAreAlreadyHoldingAnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You can not pick that up..
        /// </summary>
        public static string YouCanNotPickThatUp {
            get {
                return ResourceManager.GetString("YouCanNotPickThatUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your account credentials are invalid..
        /// </summary>
        public static string YourAccountCredentialsAreInvalid {
            get {
                return ResourceManager.GetString("YourAccountCredentialsAreInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your account has been blocked..
        /// </summary>
        public static string YourAccountHasBeenBlocked {
            get {
                return ResourceManager.GetString("YourAccountHasBeenBlocked", resourceCulture);
            }
        }
    }
}
